# Generated by Django 5.0.1 on 2024-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='em_estoque',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
